% ========================================================================
% make_table_temperature_increases_w100.m
% ------------------------------------------------------------------------
% Build LaTeX tables with forecast temperature increases by quantile,
% reference period, and forecast horizon.
%
% This script reads the AUM_temp files generated by:
%   compute_aum_temp_method0_w100.m
%   compute_aum_temp_method1_w100.m
%   compute_aum_temp_method2_w100.m
%
% and writes the corresponding LaTeX tables to Density_forecast/Tables.
%
% Globe, CRU / CRUTEM monthly quantiles, 1880--2023
% Window: w = 100
% Methods: 0, 1, 2
%
% Outputs
%   - One table without confidence intervals for each method
%   - One table with 95% confidence intervals for each method
%
% This version is portable and defines paths relative to this file.
% ========================================================================

clear; clc;

% -------------------------------------------------------------------------
% Portable paths
% -------------------------------------------------------------------------
THIS_DIR = fileparts(mfilename('fullpath'));

FIG_DIR = fullfile(THIS_DIR,'Figures'); %#ok<NASGU>
TAB_DIR = fullfile(THIS_DIR,'Tables');
RES_DIR = fullfile(THIS_DIR,'Results');

if ~exist(TAB_DIR,'dir'), mkdir(TAB_DIR); end
if ~exist(RES_DIR,'dir'), mkdir(RES_DIR); end

% -------------------------------------------------------------------------
% Settings
% -------------------------------------------------------------------------
methods = 0:2;

rows = {'q05','q10','q20','q30','q40','q50','q60','q70','q80','q90','q95'};
periods = {'1880-1900', '1986-2005', '1995-2014'};
horizon_labels = {'h=1, 2024', 'h=10, 2033', 'h=25, 2048', 'h=77, 2100'};

% Note: the original scripts used h=1,10,25,78 with year labels
% 2023,2032,2047,2100. The density forecasts are produced from the
% post-sample forecast path. The labels below follow the final paper table
% convention; change only if the paper source uses the old labels.

% -------------------------------------------------------------------------
% Build tables method by method
% -------------------------------------------------------------------------
for m = methods

    input_file = fullfile(RES_DIR, sprintf('AUM_temp_Globe_1880_2023_method%d_w100.mat',m));
    assert(exist(input_file,'file')==2, 'Required file not found: %s', input_file);

    S = load(input_file);
    assert(isfield(S,'AUM_temp'), 'File does not contain AUM_temp: %s', input_file);
    AUM_temp = S.AUM_temp;

    % Table without confidence intervals
    table_caption = sprintf(['Temperature quantile increases by reference periods and horizons, ' ...
        'method %d, w=100 (CRU data, Globe 1880--2023)'], m);
    table_label = sprintf('tab-aum-temp-Globe-1880-2023-method%d-w100', m);
    output_file = fullfile(TAB_DIR, sprintf('Table_aum_temp_Globe_1880_2023_method%d_w100.tex',m));

    write_aum_table(output_file, AUM_temp.data, [], [], rows, periods, horizon_labels, ...
        table_caption, table_label, false);

    % Table with confidence intervals
    assert(isfield(AUM_temp,'ci05') && isfield(AUM_temp,'ci95'), ...
        'AUM_temp must contain ci05 and ci95 for method %d.', m);

    table_caption_ci = sprintf(['Temperature quantile increases by reference periods and horizons, ' ...
        'method %d, w=100 (CRU data, Globe 1880--2023)'], m);
    table_label_ci = sprintf('tab-aum-temp-Globe-1880-2023-method%d-w100-ci', m);
    output_file_ci = fullfile(TAB_DIR, sprintf('Table_aum_temp_Globe_1880_2023_method%d_w100_ci.tex',m));

    write_aum_table(output_file_ci, AUM_temp.data, AUM_temp.ci05, AUM_temp.ci95, ...
        rows, periods, horizon_labels, table_caption_ci, table_label_ci, true);

    fprintf('Written tables for method %d:\n', m);
    fprintf('  %s\n', output_file);
    fprintf('  %s\n', output_file_ci);
end

fprintf('\nAll temperature-increase tables written to:\n%s\n', TAB_DIR);

% ========================================================================
% Local helper
% ========================================================================
function write_aum_table(output_file, data, ci05, ci95, rows, periods, horizon_labels, ...
    table_caption, table_label, include_ci)

    [Q,P,H] = size(data);
    assert(Q == numel(rows), 'Number of quantiles does not match row labels.');
    assert(P == numel(periods), 'Number of periods does not match period labels.');
    assert(H == numel(horizon_labels), 'Number of horizons does not match horizon labels.');

    fid = fopen(output_file,'w');
    assert(fid > 0, 'Could not open output file: %s', output_file);

    cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid,'\\begin{table}[!htbp]\n');
    fprintf(fid,'\\centering\n');
    fprintf(fid,'\\caption{%s}\n', table_caption);
    fprintf(fid,'\\label{%s}\n', table_label);
    fprintf(fid,'\\scalebox{0.70}{%%\n');
    fprintf(fid,'\\begin{tabular}{ll|cccc}\n');
    fprintf(fid,'\\hline\\hline\n');

    fprintf(fid,'quantile & period');
    for h = 1:H
        fprintf(fid,' & \\rotatebox{90}{%s}', horizon_labels{h});
    end
    fprintf(fid,' \\\\ \\hline\n');

    for q = 1:Q
        for p = 1:P
            if p == 1
                q_label = rows{q};
            else
                q_label = '';
            end

            fprintf(fid,'%s & %s', q_label, periods{p});
            for h = 1:H
                fprintf(fid,' & %5.2f', data(q,p,h));
            end
            fprintf(fid,' \\\\ \n');

            if include_ci
                fprintf(fid,' & ');
                for h = 1:H
                    fprintf(fid,' & (%5.2f,%5.2f)', ci05(q,p,h), ci95(q,p,h));
                end
                fprintf(fid,' \\\\ \n');
            end
        end
        fprintf(fid,'\\cline{2-6}\n');
    end

    fprintf(fid,'\\hline\\hline\n');
    fprintf(fid,'\\end{tabular}}\n');
    fprintf(fid,'\\end{table}\n');
end
